# 碳排放交易實驗配置文件
# 統一管理各階段的常數和設定
# 版本：5.0
# 最後更新：2025-07-10

# ====================================
# 實驗模式切換（主開關）
# ====================================
experiment_mode:
  # 主開關：true = 測試模式, false = 正式模式
  test_mode_enabled: false
  
  # 模式說明
  # - 測試模式：2人一組，3回合，簡化參數，方便快速測試
  # - 正式模式：12人一組，12回合，完整參數，用於正式實驗

# ====================================
# 通用設定（根據模式自動選擇）
# ====================================
general:
  # 基本參數（正式模式）
  players_per_group: 12  # 正式實驗：N 人一組
  num_rounds: 12 # 正式實驗：T 回合
  max_production: 50 # （實際上用不到）
  random_dominant_firm_each_round: False
  carbon_real_world_rate: 0.1 # 1 單位實驗中碳排放 = 現實生活多少單位
  
  # 市場價格隨機抽取設定 （已經不再使用）
  market_price_random_draw:
    base_prices: [25, 35]  # 基礎價格選項
    variations: [0]  # 變動幅度選項
    min_price: 1  # 最低價格
  
  # 廠商角色參數
  dominant_firm:
    mc_range: [2, 3]  # 邊際成本係數範圍 （已經不再使用）
    emission_per_unit: 2  # 每單位碳排放
    max_production: 20    # 最大生產量
    
  non_dominant_firm:
    mc_range: [4, 5]  # 邊際成本係數範圍  （已經不再使用）
    emission_per_unit: 1  # 每單位碳排放
    max_production: 8     # 最大生產量
  
  # 角色分配設定（正式模式）
  role_assignment:
    dominant_firm_count: 3  # 主導廠商數量
    non_dominant_firm_count: 9  # 其他廠商數量
    ensure_player1_dominant: false  # 正式實驗不需要確保1號玩家為主導廠商
  
  # 隨機擾動參數
  random_disturbance:
    range: [-1, 1]  # 生產成本隨機擾動範圍

# ====================================
# 測試模式覆蓋設定
# ====================================
test_mode_overrides:
  # 測試模式下的基本參數
  general:
    players_per_group: 2  # 測試模式：2人一組
    num_rounds: 3  # 測試模式：3回合
    max_production: 20  # 測試模式：最大生產量
    
    # 角色分配設定（測試模式）
    role_assignment:
      dominant_firm_count: 1  # 測試模式：1個主導廠商
      non_dominant_firm_count: 1  # 測試模式：1個其他廠商
      ensure_player1_dominant: true  # 測試模式確保1號玩家為主導廠商
    
    # 市場價格（測試模式簡化）
    market_price_random_draw:
      base_prices: [25, 35]  # 簡化的基礎價格選項 （已經不再使用）
      variations: [0]  # 簡化的變動幅度 （已經不再使用）
      min_price: 1
  
  # 測試模式下的階段設定覆蓋
  stages:
    control:
      initial_capital: 1000 # 測試模式較高初始資金
      
    carbon_tax:
      initial_capital: 1000
      tax_random_selection:
        rates: [6]  # 測試模式簡化稅率選項
        
    muda:
      initial_capital: 1000  # 測試模式大量資金
      trading_time: 60  # 測試模式縮短交易時間
      item_price_options: [30, 35]  # 測試模式簡化價格選項
      num_rounds: 2
      
      
    carbon_trading:
      initial_capital: 1000
      trading_time: 60  # 測試模式縮短交易時間
      carbon_allowance_per_player: 5  # 測試模式較少碳權
      
      # 測試模式的碳權分配設定
      optimal_allocation:
        cap_multipliers: [1.0]  # 測試模式只用標準倍率

# ====================================
# 各階段設定（正式模式）
# ====================================
stages:
  control:
    name_in_url: 'Stage_Control'
    display_name: "對照組"
    initial_capital: 0
    description: "對照組：受試者直接決定生產量，不受碳排放限制，也不需繳納碳稅"
    
  carbon_tax:
    name_in_url: 'Stage_CarbonTax'
    display_name: "碳稅組"
    initial_capital: 0
    description: "碳稅組：受試者直接決定生產量，但需為每單位碳排放繳納碳稅"
    # 碳稅隨機抽取設定 （已經不再使用）
    tax_random_selection:
      rates: [3, 6, 9] 
      
  muda:
    name_in_url: 'Stage_MUDA'
    display_name: "MUDA"
    initial_capital: 1000
    trading_time: 120
    num_rounds: 4 # 正式實驗讓受試者練習 MUDA 的回合數
    item_name: "碳權"
    reset_cash_each_round: true
    description: "MUDA：純交易練習回合，讓受試者熟悉交易市場介面操作"
    # 碳權價格隨機抽取設定
    item_price_options: [25, 30, 35, 40]  # 碳權價格選項
    
  carbon_trading:
    name_in_url: 'Stage_CarbonTrading'
    display_name: "碳交易組"
    initial_capital: 1000
    trading_time: 120
    carbon_allowance_per_player: 10
    reset_cash_each_round: true  # 每輪重置現金
    description: "碳交易組：受試者在碳權交易市場進行買賣，確定手上持有碳權數量後，再決定生產量。"
    
    # 社會最適產量與碳權分配設定
    optimal_allocation:
      # 固定參數設定
      use_fixed_price: false  # 是否使用固定市場價格（而非隨機抽取）
      fixed_market_price: 10  # 固定市場價格時用的價格
      social_cost_per_unit_carbon: 6  # 每單位碳的社會成本 c
      
      # 配額分配設定
      cap_multipliers: [0.5, 1.0, 1.5]  # 配額倍率選項 （已經不再使用）
      allocation_method: "equal_with_random_remainder"  # 分配方法
      round_cap_total: true  # 是否將配額總數四捨五入為整數
      
    # 輸出設定
    output:
      show_detailed_calculation: true  # 是否顯示詳細計算過程
      decimal_places: 2  # 小數位數
      console_output_format: "detailed"  # 控制台輸出格式: "simple" 或 "detailed"
  
  payment_info:
    name_in_url: 'Stage_Payment_Info'
    display_name: "報酬結算與收據資訊"
    description: "計算總報酬並收集收據資訊"

  survey:
    name_in_url: 'Stage_Survey'
    display_name: "問卷"
    description: "實驗後問卷"

# ====================================
# 12 組隨機參數組合
# ====================================
preset_parameter_matrix:
  columns: [market_price, tax_rate, carbon_multiplier, dominant_mc, non_dominant_mc]
  values:
    - [25, 3, 0.5, 2, 4]
    - [25, 3, 0.5, 3, 5]
    - [25, 6, 1.0, 2, 4]
    - [25, 6, 1.0, 3, 5]
    - [25, 9, 1.5, 2, 4]
    - [25, 9, 1.5, 3, 5]
    - [35, 3, 0.5, 2, 4]
    - [35, 3, 0.5, 3, 5]
    - [35, 6, 1.0, 2, 4]
    - [35, 6, 1.0, 3, 5]
    - [35, 9, 1.5, 2, 4]
    - [35, 9, 1.5, 3, 5]

# ====================================
# 頁面流程配置
# ====================================
page_sequences: # 但似乎沒有用到？
  control: ['Introduction', 'ReadyWaitPage', 'ProductionDecision', 'ResultsWaitPage', 'Results', 'WaitForInstruction']
  carbon_tax: ['Introduction', 'ReadyWaitPage', 'ProductionDecision', 'ResultsWaitPage', 'Results', 'WaitForInstruction']
  muda: ['Introduction', 'ReadyWaitPage', 'TradingMarket', 'ResultsWaitPage', 'Results', 'WaitForInstruction']
  carbon_trading: ['Introduction', 'ReadyWaitPage', 'TradingMarket', 'ProductionDecision', 'ResultsWaitPage', 'Results', 'WaitForInstruction']
  payment_info: ['PaymentInfo', 'WaitForInstruction']
  survey: ['BasicInfo', 'Survey', 'ByePage']

# ====================================
# 實驗設定
# ====================================
experiment_settings:
  # 最終報酬計算
  final_payoff:
    random_round_selection: true  # 隨機選擇回合計算最終報酬
    
  # 調試設定
  debug:
    show_debug_info: false  # 是否顯示調試信息
    console_logging: true   # 是否輸出控制台日誌

# ====================================
# 國際化設定
# ====================================
ui_text:
  zh_tw:
    treatment_names:
      control: "對照"
      carbon_tax: "碳稅"
      muda: "MUDA"
      carbon_trading: "碳交易"
    common_labels:
      production: "生產量"
      revenue: "收入"
      cost: "成本"
      profit: "利潤"
      cash: "現金"
      round: "回合"
      market_price: "市場價格"
      carbon_emission: "碳排放量"
      carbon_tax: "碳稅"
      carbon_allowance: "碳權"
      trading_time: "交易時間"
      base_tax_rate: "基礎稅率"
      tax_variation: "稅率變動"
      item_price: "物品價格" 
